version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "2445:5678"

    environment:
      # Base de données
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}  # Même variable que PostgreSQL
      
      # Configuration de base
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_EDITOR_BASE_URL=https://peaceful-buck-separately.ngrok-free.app
      - WEBHOOK_URL=https://peaceful-buck-separately.ngrok-free.app
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem

      # Timezone
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local_files:/files
    depends_on:
      postgres:
        condition: service_healthy  # Attendre que PostgreSQL soit prêt
    networks:
      - n8n_network

  postgres:
    image: postgres:17
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=N8N_BASIC_AUTH_USER
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Varable uni
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

volumes:
  n8n_data:
  postgres_data:

networks:
  n8n_network:
    driver: bridge